# Generated by Django 3.2.6 on 2021-08-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relationsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
