# Generated by Django 3.2.6 on 2021-08-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relationsapp', '0002_alter_studentdata_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='name',
            new_name='sir_name',
        ),
    ]
