# Generated by Django 3.2.6 on 2021-08-14 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Relationsapp', '0003_rename_name_lecturer_sir_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='depbranch',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='depbranch',
            field=models.ManyToManyField(to='Relationsapp.Departmentbranch'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Relationsapp.departmentbranch'),
        ),
    ]
