# Generated by Django 3.2.6 on 2021-08-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relationsapp', '0004_auto_20210814_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='sir_name',
            new_name='Lecturer_name',
        ),
    ]
